services:
  
  backend:
    build: .
    environment:
      - POSTGRES_HOST=database
    ports: 
      - "3000:3000"
    depends_on:
      - database
      - redis
    networks:
      - network
  
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - network
  
  redis: 
    image: redis
    ports:
      - "6379:6379"
    networks:
      - network

volumes:
  database:
networks:
  network: