services:
  
  backend:
    build: .
    environment:
      - POSTGRES_HOST=database
    ports: 
      - "3000:3000"
    depends_on:
      - database
  
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: 